name: C++ Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/build-cpp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/build-cpp.yml'

jobs:
  build-and-test:
    name: Build and Test C++ on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Set up Developer Command Prompt
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    # Set up CMake
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    # Install Ninja
    - name: Install Ninja
      run: |
        choco install ninja -y
        ninja --version

    # Set up vcpkg cache
    - name: Cache vcpkg
      uses: actions/cache@v3
      id: vcpkg-cache
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          !${{ github.workspace }}/vcpkg/buildtrees
          !${{ github.workspace }}/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('cpp/cmake/CMakeLists.txt') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    # Clone and bootstrap vcpkg if cache miss
    - name: Checkout vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: microsoft/vcpkg
        path: vcpkg

    - name: Bootstrap vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.workspace }}/vcpkg
        .\bootstrap-vcpkg.bat

    # Install dependencies with vcpkg
    - name: Install dependencies with vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg install spdlog:x64-windows gtest:x64-windows catch2:x64-windows zlib:x64-windows rapidjson:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg integrate install

    # Set up build cache
    - name: Cache build directory
      uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          ${{ github.workspace }}/build
          !${{ github.workspace }}/build/Testing
        key: build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('cpp/**/*.cpp', 'cpp/**/*.h', 'cpp/cmake/**') }}
        restore-keys: |
          build-${{ runner.os }}-${{ matrix.build_type }}-

    # Configure CMake
    - name: Configure CMake
      run: |
        cmake -S ${{ github.workspace }}/cpp/cmake \
          -B ${{ github.workspace }}/build \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_STANDARD=20 \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    # Build
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    # Test
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: |
        ctest -C ${{ matrix.build_type }} --output-on-failure

    # Upload build artifacts
    - name: Upload build artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: cpp-build-windows-${{ matrix.build_type }}
        path: |
          ${{ github.workspace }}/build/Testing
          ${{ github.workspace }}/build/*.log
        retention-days: 7
