name: C++ Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/build-cpp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - '.github/workflows/build-cpp.yml'

jobs:
  build-and-test:
    name: Build and Test C++ on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.27.0"
        ninjaVersion: "~1.11.0"

    # Set up vcpkg cache
    - name: Cache vcpkg
      uses: actions/cache@v4
      id: vcpkg-cache
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          !${{ github.workspace }}/vcpkg/buildtrees
          !${{ github.workspace }}/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('cpp/CMakeLists.txt') }}-v1
        restore-keys: |
          vcpkg-${{ runner.os }}-v1

    # Set up build cache
    - name: Cache build directory
      uses: actions/cache@v4
      id: build-cache
      with:
        path: |
          ${{ github.workspace }}/build
          !${{ github.workspace }}/build/Testing
        key: build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('cpp/**/*.cpp', 'cpp/**/*.h', 'cpp/**/*.hpp', 'cpp/CMakeLists.txt') }}-v1
        restore-keys: |
          build-${{ runner.os }}-${{ matrix.build_type }}-v1

    - name: Checkout vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        path: vcpkg

    - name: Bootstrap vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.workspace }}/vcpkg
        .\bootstrap-vcpkg.bat -disableMetrics
      shell: cmd

    # Make vcpkg installation more robust with separate steps
    - name: Install core dependencies with vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg install spdlog:x64-windows gtest:x64-windows rapidjson:x64-windows zlib:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg integrate install
      shell: cmd

    - name: Install MQTT dependency with vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg install async-mqtt[tls]:x64-windows
      shell: cmd
      continue-on-error: true

    - name: Verify Ninja installation
      run: |
        ninja --version
      shell: cmd

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_STANDARD=20 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: cmd

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel
      shell: cmd

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: |
        ctest -C ${{ matrix.build_type }} --output-on-failure --timeout 300
      shell: cmd
      continue-on-error: true

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cpp-build-windows-${{ matrix.build_type }}
        path: |
          ${{ github.workspace }}/build/Testing
          ${{ github.workspace }}/build/*.log
          ${{ github.workspace }}/build/CMakeFiles/CMakeOutput.log
          ${{ github.workspace }}/build/CMakeFiles/CMakeError.log
        retention-days: 7

    - name: Check for test failures
      if: always()
      run: |
        if (Test-Path ${{ github.workspace }}/build/Testing/Temporary/LastTest.log) {
          $content = Get-Content ${{ github.workspace }}/build/Testing/Temporary/LastTest.log -Raw
          if ($content -match "Failed") {
            Write-Host "::error::Test failures detected, check the logs for details"
            exit 1
          }
        }
      shell: pwsh
